#!/usr/bin/bash

annot  = read.table('/home/user/Desktop/NA.txt', row.names=1, header=TRUE);

# Match probes in the data set to the probe IDs in the annotation file

probes = names(log_counts_t)

probes2annot = match(probes, annot$substanceBXH)

# Get the corresponding Locuis Link IDs

allLLIDs = annot$LocusLinkID[probes2annot];

# $ Choose interesting modules

intModules = c("black" , "blue" , "cyan")


for (module in intModules)

{

# Select module probes

modGenes = (module_colours==module)

# Get their entrez ID codes

modLLIDs = allLLIDs[modGenes];

# Write them into a file

fileName = paste("LocusLinkIDs-", module, ".txt", sep="");

write.table(as.data.frame(modLLIDs), file = fileName,

row.names = FALSE, col.names = FALSE)

}

# As background in the enrichment analysis, we will use all probes in the analysis.

fileName = paste("LocusLinkIDs-all.txt", sep="");

write.table(as.data.frame(allLLIDs), file = fileName,

~

